-- Add remaining NCAA schools (Division I, II, III), NAIA, and JUCO schools
BEGIN;

-- First, update the ncaa_division enum to include NAIA and JUCO
ALTER TYPE ncaa_division ADD VALUE IF NOT EXISTS 'NAIA';
ALTER TYPE ncaa_division ADD VALUE IF NOT EXISTS 'JUCO';

-- Add remaining Division I schools (completing the 358 total)
INSERT INTO public.schools (name, division)
VALUES
    -- ACC Conference (additional schools)
    ('Boston College', 'I'),
    ('Clemson University', 'I'),
    ('Duke University', 'I'),
    ('Florida State University', 'I'),
    ('Georgia Institute of Technology', 'I'),
    ('University of Louisville', 'I'),
    ('University of Miami', 'I'),
    ('North Carolina State University', 'I'),
    ('University of North Carolina at Chapel Hill', 'I'),
    ('University of Notre Dame', 'I'),
    ('University of Pittsburgh', 'I'),
    ('Syracuse University', 'I'),
    ('Virginia Tech', 'I'),
    ('University of Virginia', 'I'),
    ('Wake Forest University', 'I'),

    -- Big Ten Conference
    ('University of Illinois at Urbana-Champaign', 'I'),
    ('Indiana University', 'I'),
    ('University of Iowa', 'I'),
    ('University of Maryland', 'I'),
    ('University of Michigan', 'I'),
    ('Michigan State University', 'I'),
    ('University of Minnesota', 'I'),
    ('University of Nebraska', 'I'),
    ('Northwestern University', 'I'),
    ('Ohio State University', 'I'),
    ('Penn State University', 'I'),
    ('Purdue University', 'I'),
    ('Rutgers University', 'I'),
    ('University of Wisconsin', 'I'),

    -- SEC Conference
    ('University of Alabama', 'I'),
    ('University of Arkansas', 'I'),
    ('Auburn University', 'I'),
    ('University of Florida', 'I'),
    ('University of Georgia', 'I'),
    ('University of Kentucky', 'I'),
    ('Louisiana State University', 'I'),
    ('University of Mississippi', 'I'),
    ('Mississippi State University', 'I'),
    ('University of Missouri', 'I'),
    ('University of South Carolina', 'I'),
    ('University of Tennessee', 'I'),
    ('Texas A&M University', 'I'),
    ('Vanderbilt University', 'I'),

    -- Mountain West Conference
    ('Air Force Academy', 'I'),
    ('Boise State University', 'I'),
    ('Colorado State University', 'I'),
    ('Fresno State University', 'I'),
    ('University of Nevada, Las Vegas', 'I'),
    ('University of Nevada, Reno', 'I'),
    ('University of New Mexico', 'I'),
    ('San Diego State University', 'I'),
    ('San Jose State University', 'I'),
    ('University of Wyoming', 'I'),
    ('Utah State University', 'I'),
    ('Hawaii University', 'I'),

    -- Conference USA
    ('Florida International University', 'I'),
    ('Liberty University', 'I'),
    ('Louisiana Tech University', 'I'),
    ('Middle Tennessee State University', 'I'),
    ('New Mexico State University', 'I'),
    ('Old Dominion University', 'I'),
    ('Sam Houston State University', 'I'),
    ('University of Texas at El Paso', 'I'),
    ('Western Kentucky University', 'I'),
    ('Jacksonville State University', 'I'),

    -- MAC Conference
    ('University of Akron', 'I'),
    ('Ball State University', 'I'),
    ('Bowling Green State University', 'I'),
    ('University at Buffalo', 'I'),
    ('Central Michigan University', 'I'),
    ('Eastern Michigan University', 'I'),
    ('Kent State University', 'I'),
    ('Miami University', 'I'),
    ('Northern Illinois University', 'I'),
    ('Ohio University', 'I'),
    ('University of Toledo', 'I'),
    ('Western Michigan University', 'I'),

    -- Sun Belt Conference
    ('Appalachian State University', 'I'),
    ('Arkansas State University', 'I'),
    ('Coastal Carolina University', 'I'),
    ('Georgia Southern University', 'I'),
    ('Georgia State University', 'I'),
    ('James Madison University', 'I'),
    ('Louisiana Lafayette University', 'I'),
    ('University of Louisiana at Monroe', 'I'),
    ('Marshall University', 'I'),
    ('Old Dominion University', 'I'),
    ('South Alabama University', 'I'),
    ('Southern Miss University', 'I'),
    ('Texas State University', 'I'),
    ('Troy University', 'I'),

    -- Ivy League
    ('Brown University', 'I'),
    ('Columbia University', 'I'),
    ('Cornell University', 'I'),
    ('Dartmouth College', 'I'),
    ('Harvard University', 'I'),
    ('University of Pennsylvania', 'I'),
    ('Princeton University', 'I'),
    ('Yale University', 'I'),

    -- Patriot League
    ('American University', 'I'),
    ('Army West Point', 'I'),
    ('Bucknell University', 'I'),
    ('Colgate University', 'I'),
    ('College of the Holy Cross', 'I'),
    ('Lafayette College', 'I'),
    ('Lehigh University', 'I'),
    ('Loyola University Maryland', 'I'),
    ('Navy Midshipmen', 'I'),
    ('Boston University', 'I'),

    -- Atlantic 10 Conference
    ('University of Dayton', 'I'),
    ('University of Davidson', 'I'),
    ('Duquesne University', 'I'),
    ('Fordham University', 'I'),
    ('George Mason University', 'I'),
    ('George Washington University', 'I'),
    ('La Salle University', 'I'),
    ('University of Massachusetts', 'I'),
    ('University of Rhode Island', 'I'),
    ('University of Richmond', 'I'),
    ('Saint Joseph''s University', 'I'),
    ('St. Bonaventure University', 'I'),
    ('Saint Louis University', 'I'),
    ('Virginia Commonwealth University', 'I'),

    -- Colonial Athletic Association
    ('University of Delaware', 'I'),
    ('Drexel University', 'I'),
    ('Elon University', 'I'),
    ('Hofstra University', 'I'),
    ('James Madison University', 'I'),
    ('Monmouth University', 'I'),
    ('Northeastern University', 'I'),
    ('Towson University', 'I'),
    ('College of William & Mary', 'I'),
    ('University of North Carolina Wilmington', 'I'),

    -- Big Sky Conference
    ('University of California, Davis', 'I'),
    ('Eastern Washington University', 'I'),
    ('Idaho State University', 'I'),
    ('University of Montana', 'I'),
    ('Montana State University', 'I'),
    ('University of Northern Colorado', 'I'),
    ('Northern Arizona University', 'I'),
    ('Portland State University', 'I'),
    ('Sacramento State University', 'I'),
    ('University of Southern Utah', 'I'),
    ('Weber State University', 'I'),
    ('University of Idaho', 'I'),

    -- Missouri Valley Conference
    ('Bradley University', 'I'),
    ('Drake University', 'I'),
    ('Evansville University', 'I'),
    ('Illinois State University', 'I'),
    ('Indiana State University', 'I'),
    ('Loyola University Chicago', 'I'),
    ('University of Missouri State', 'I'),
    ('University of Northern Iowa', 'I'),
    ('Southern Illinois University', 'I'),
    ('Valparaiso University', 'I'),

    -- Horizon League
    ('Cleveland State University', 'I'),
    ('Detroit Mercy University', 'I'),
    ('University of Illinois at Chicago', 'I'),
    ('IUPUI', 'I'),
    ('Milwaukee University', 'I'),
    ('Northern Kentucky University', 'I'),
    ('Oakland University', 'I'),
    ('Purdue University Fort Wayne', 'I'),
    ('Robert Morris University', 'I'),
    ('Wright State University', 'I'),
    ('Youngstown State University', 'I'),

    -- Additional Division I schools
    ('Abilene Christian University', 'I'),
    ('Alabama A&M University', 'I'),
    ('Alabama State University', 'I'),
    ('Albany University', 'I'),
    ('Alcorn State University', 'I'),
    ('American University', 'I'),
    ('Austin Peay State University', 'I'),
    ('Belmont University', 'I'),
    ('Bethune-Cookman University', 'I'),
    ('Binghamton University', 'I'),
    ('California Polytechnic State University', 'I'),
    ('California State University, Bakersfield', 'I'),
    ('California State University, Fullerton', 'I'),
    ('California State University, Northridge', 'I'),
    ('Campbell University', 'I'),
    ('Canisius College', 'I'),
    ('Central Connecticut State University', 'I'),
    ('Charleston Southern University', 'I'),
    ('Chicago State University', 'I'),
    ('The Citadel', 'I'),
    ('Coppin State University', 'I'),
    ('Delaware State University', 'I'),
    ('Denver University', 'I'),
    ('East Tennessee State University', 'I'),
    ('Eastern Illinois University', 'I'),
    ('Eastern Kentucky University', 'I'),
    ('Fairfield University', 'I'),
    ('Fairleigh Dickinson University', 'I'),
    ('Florida A&M University', 'I'),
    ('Florida Gulf Coast University', 'I'),
    ('Furman University', 'I'),
    ('Gonzaga University', 'I'),
    ('Grambling State University', 'I'),
    ('Hampton University', 'I'),
    ('Hartford University', 'I'),
    ('High Point University', 'I'),
    ('Howard University', 'I'),
    ('Iona College', 'I'),
    ('Jackson State University', 'I'),
    ('Jacksonville University', 'I'),
    ('Kennesaw State University', 'I'),
    ('Lamar University', 'I'),
    ('Lipscomb University', 'I'),
    ('Long Island University', 'I'),
    ('Longwood University', 'I'),
    ('Maine University', 'I'),
    ('Manhattan College', 'I'),
    ('Marist College', 'I'),
    ('McNeese State University', 'I'),
    ('Mercer University', 'I'),
    ('Morehead State University', 'I'),
    ('Morgan State University', 'I'),
    ('Murray State University', 'I'),
    ('New Hampshire University', 'I'),
    ('Niagara University', 'I'),
    ('Nicholls State University', 'I'),
    ('Norfolk State University', 'I'),
    ('North Carolina A&T State University', 'I'),
    ('North Carolina Central University', 'I'),
    ('North Dakota State University', 'I'),
    ('University of North Dakota', 'I'),
    ('Oral Roberts University', 'I'),
    ('Pacific University', 'I'),
    ('Pennsylvania State University', 'I'),
    ('Pepperdine University', 'I'),
    ('Prairie View A&M University', 'I'),
    ('Presbyterian College', 'I'),
    ('Quinnipiac University', 'I'),
    ('Radford University', 'I'),
    ('Rider University', 'I'),
    ('Sacred Heart University', 'I'),
    ('Saint Francis University', 'I'),
    ('Saint Mary''s College of California', 'I'),
    ('Saint Peter''s University', 'I'),
    ('Samford University', 'I'),
    ('Santa Clara University', 'I'),
    ('Savannah State University', 'I'),
    ('Seattle University', 'I'),
    ('Siena College', 'I'),
    ('South Carolina State University', 'I'),
    ('South Dakota State University', 'I'),
    ('University of South Dakota', 'I'),
    ('Southeastern Louisiana University', 'I'),
    ('Southern Illinois University Edwardsville', 'I'),
    ('Southern University', 'I'),
    ('Stephen F. Austin State University', 'I'),
    ('Stetson University', 'I'),
    ('Stony Brook University', 'I'),
    ('Tennessee Martin University', 'I'),
    ('Tennessee State University', 'I'),
    ('Tennessee Tech University', 'I'),
    ('Texas A&M University-Commerce', 'I'),
    ('Texas A&M University-Corpus Christi', 'I'),
    ('Texas Southern University', 'I'),
    ('UMBC', 'I'),
    ('UC Irvine', 'I'),
    ('UC Riverside', 'I'),
    ('UC San Diego', 'I'),
    ('UC Santa Barbara', 'I'),
    ('UMass Lowell', 'I'),
    ('Vermont University', 'I'),
    ('Wagner College', 'I'),
    ('Wichita State University', 'I'),
    ('Winthrop University', 'I'),
    ('Wofford College', 'I')
ON CONFLICT (name) DO NOTHING;

-- Add major Division II schools
INSERT INTO public.schools (name, division)
VALUES
    -- Top Division II schools by region
    ('Adams State University', 'II'),
    ('Angelo State University', 'II'),
    ('Azusa Pacific University', 'II'),
    ('Bentley University', 'II'),
    ('California State University, Chico', 'II'),
    ('California State University, Los Angeles', 'II'),
    ('California State University, Monterey Bay', 'II'),
    ('California State University, Stanislaus', 'II'),
    ('Central Washington University', 'II'),
    ('Cheyney University of Pennsylvania', 'II'),
    ('Colorado Mesa University', 'II'),
    ('Colorado School of Mines', 'II'),
    ('Columbus State University', 'II'),
    ('Concordia University', 'II'),
    ('Delta State University', 'II'),
    ('Dixie State University', 'II'),
    ('Drury University', 'II'),
    ('Emporia State University', 'II'),
    ('Ferris State University', 'II'),
    ('Florida Institute of Technology', 'II'),
    ('Fort Hays State University', 'II'),
    ('Grand Valley State University', 'II'),
    ('Harding University', 'II'),
    ('Henderson State University', 'II'),
    ('Humboldt State University', 'II'),
    ('Indianapolis University', 'II'),
    ('Lake Superior State University', 'II'),
    ('Lewis University', 'II'),
    ('Lincoln University', 'II'),
    ('Lindenwood University', 'II'),
    ('Lock Haven University', 'II'),
    ('Mesa State College', 'II'),
    ('Michigan Technological University', 'II'),
    ('Midwestern State University', 'II'),
    ('Minnesota State University, Mankato', 'II'),
    ('Missouri Southern State University', 'II'),
    ('Missouri Western State University', 'II'),
    ('Montana State University Billings', 'II'),
    ('New Mexico Highlands University', 'II'),
    ('North Dakota State University', 'II'),
    ('Northeastern State University', 'II'),
    ('Northern Michigan University', 'II'),
    ('Northern State University', 'II'),
    ('Northwest Missouri State University', 'II'),
    ('Northwest Nazarene University', 'II'),
    ('Pittsburg State University', 'II'),
    ('Queens University of Charlotte', 'II'),
    ('Rollins College', 'II'),
    ('Saint Anselm College', 'II'),
    ('Saint Rose College', 'II'),
    ('Seattle Pacific University', 'II'),
    ('Shippensburg University', 'II'),
    ('Slippery Rock University', 'II'),
    ('Sonoma State University', 'II'),
    ('Southern Arkansas University', 'II'),
    ('Southern Connecticut State University', 'II'),
    ('Southern Illinois University Edwardsville', 'II'),
    ('Southwest Baptist University', 'II'),
    ('Tarleton State University', 'II'),
    ('Texas A&M International University', 'II'),
    ('Texas A&M University-Kingsville', 'II'),
    ('Truman State University', 'II'),
    ('Tuskegee University', 'II'),
    ('University of Alabama in Huntsville', 'II'),
    ('University of Arkansas at Monticello', 'II'),
    ('University of California, San Diego', 'II'),
    ('University of Central Arkansas', 'II'),
    ('University of Colorado Colorado Springs', 'II'),
    ('University of Findlay', 'II'),
    ('University of Indianapolis', 'II'),
    ('University of Minnesota Duluth', 'II'),
    ('University of Nebraska at Kearney', 'II'),
    ('University of Nebraska at Omaha', 'II'),
    ('University of North Alabama', 'II'),
    ('University of North Carolina at Pembroke', 'II'),
    ('University of North Florida', 'II'),
    ('University of Puerto Rico', 'II'),
    ('University of Tampa', 'II'),
    ('University of the Incarnate Word', 'II'),
    ('University of West Alabama', 'II'),
    ('University of West Florida', 'II'),
    ('University of Wisconsin-Parkside', 'II'),
    ('Valdosta State University', 'II'),
    ('Virginia State University', 'II'),
    ('Walsh University', 'II'),
    ('Wayne State University', 'II'),
    ('West Chester University', 'II'),
    ('West Texas A&M University', 'II'),
    ('Western Oregon University', 'II'),
    ('Western Washington University', 'II'),
    ('Winona State University', 'II'),
    ('Winston-Salem State University', 'II')
ON CONFLICT (name) DO NOTHING;

-- Add major Division III schools
INSERT INTO public.schools (name, division)
VALUES
    -- Top Division III schools
    ('Albion College', 'III'),
    ('Allegheny College', 'III'),
    ('Amherst College', 'III'),
    ('Augsburg University', 'III'),
    ('Babson College', 'III'),
    ('Bates College', 'III'),
    ('Bowdoin College', 'III'),
    ('Brandeis University', 'III'),
    ('Carleton College', 'III'),
    ('Carnegie Mellon University', 'III'),
    ('Case Western Reserve University', 'III'),
    ('Claremont McKenna College', 'III'),
    ('Colby College', 'III'),
    ('Colorado College', 'III'),
    ('Connecticut College', 'III'),
    ('Denison University', 'III'),
    ('DePauw University', 'III'),
    ('Dickinson College', 'III'),
    ('Emory University', 'III'),
    ('Franklin & Marshall College', 'III'),
    ('Gettysburg College', 'III'),
    ('Grinnell College', 'III'),
    ('Gustavus Adolphus College', 'III'),
    ('Hamilton College', 'III'),
    ('Haverford College', 'III'),
    ('Johns Hopkins University', 'III'),
    ('Kenyon College', 'III'),
    ('Lawrence University', 'III'),
    ('Macalester College', 'III'),
    ('Middlebury College', 'III'),
    ('MIT', 'III'),
    ('Mount Holyoke College', 'III'),
    ('Muhlenberg College', 'III'),
    ('New York University', 'III'),
    ('Oberlin College', 'III'),
    ('Occidental College', 'III'),
    ('Pomona College', 'III'),
    ('Reed College', 'III'),
    ('Rhodes College', 'III'),
    ('Scripps College', 'III'),
    ('Sewanee: The University of the South', 'III'),
    ('Smith College', 'III'),
    ('Swarthmore College', 'III'),
    ('Trinity College', 'III'),
    ('Tufts University', 'III'),
    ('University of Chicago', 'III'),
    ('University of Rochester', 'III'),
    ('Vassar College', 'III'),
    ('Washington and Lee University', 'III'),
    ('Washington University in St. Louis', 'III'),
    ('Wellesley College', 'III'),
    ('Wesleyan University', 'III'),
    ('Whitman College', 'III'),
    ('Williams College', 'III'),
    ('Wisconsin Lutheran College', 'III')
ON CONFLICT (name) DO NOTHING;

-- Add major NAIA schools
INSERT INTO public.schools (name, division)
VALUES
    -- Top NAIA schools
    ('Auburn University Montgomery', 'NAIA'),
    ('Avila University', 'NAIA'),
    ('Baker University', 'NAIA'),
    ('Bellevue University', 'NAIA'),
    ('Benedictine College', 'NAIA'),
    ('Bethany College', 'NAIA'),
    ('Bethel College', 'NAIA'),
    ('Biola University', 'NAIA'),
    ('Briar Cliff University', 'NAIA'),
    ('California Baptist University', 'NAIA'),
    ('Carroll College', 'NAIA'),
    ('Cedarville University', 'NAIA'),
    ('Central Methodist University', 'NAIA'),
    ('Clarke University', 'NAIA'),
    ('College of Idaho', 'NAIA'),
    ('Columbia College', 'NAIA'),
    ('Concordia University Nebraska', 'NAIA'),
    ('Cornerstone University', 'NAIA'),
    ('Culver-Stockton College', 'NAIA'),
    ('Davenport University', 'NAIA'),
    ('Doane University', 'NAIA'),
    ('Dominican University', 'NAIA'),
    ('Dordt University', 'NAIA'),
    ('Evangel University', 'NAIA'),
    ('Faulkner University', 'NAIA'),
    ('Freed-Hardeman University', 'NAIA'),
    ('Friends University', 'NAIA'),
    ('Georgetown College', 'NAIA'),
    ('Grace College', 'NAIA'),
    ('Graceland University', 'NAIA'),
    ('Grand View University', 'NAIA'),
    ('Hastings College', 'NAIA'),
    ('Holy Family University', 'NAIA'),
    ('Huntington University', 'NAIA'),
    ('Indiana Wesleyan University', 'NAIA'),
    ('Jamestown University', 'NAIA'),
    ('Kansas Wesleyan University', 'NAIA'),
    ('Kentucky State University', 'NAIA'),
    ('Lindsey Wilson College', 'NAIA'),
    ('MidAmerica Nazarene University', 'NAIA'),
    ('Midland University', 'NAIA'),
    ('Missouri Valley College', 'NAIA'),
    ('Morningside College', 'NAIA'),
    ('Mount Mercy University', 'NAIA'),
    ('Mount Vernon Nazarene University', 'NAIA'),
    ('Northwestern College', 'NAIA'),
    ('Oklahoma Baptist University', 'NAIA'),
    ('Oklahoma Christian University', 'NAIA'),
    ('Oklahoma Wesleyan University', 'NAIA'),
    ('Olivet Nazarene University', 'NAIA'),
    ('Ottawa University', 'NAIA'),
    ('Park University', 'NAIA'),
    ('Point University', 'NAIA'),
    ('Robert Morris University Illinois', 'NAIA'),
    ('Rocky Mountain College', 'NAIA'),
    ('Saint Francis University', 'NAIA'),
    ('Saint Xavier University', 'NAIA'),
    ('Siena Heights University', 'NAIA'),
    ('Southern Nazarene University', 'NAIA'),
    ('Spring Arbor University', 'NAIA'),
    ('Sterling College', 'NAIA'),
    ('Tabor College', 'NAIA'),
    ('Taylor University', 'NAIA'),
    ('Trinity International University', 'NAIA'),
    ('Union College', 'NAIA'),
    ('University of Great Falls', 'NAIA'),
    ('University of Jamestown', 'NAIA'),
    ('University of Saint Mary', 'NAIA'),
    ('University of Sioux Falls', 'NAIA'),
    ('Viterbo University', 'NAIA'),
    ('Warner University', 'NAIA'),
    ('William Carey University', 'NAIA'),
    ('William Woods University', 'NAIA')
ON CONFLICT (name) DO NOTHING;

-- Add major JUCO schools
INSERT INTO public.schools (name, division)
VALUES
    -- Top JUCO schools by region
    ('Allegany College of Maryland', 'JUCO'),
    ('Arizona Western College', 'JUCO'),
    ('Barton Community College', 'JUCO'),
    ('Blinn College', 'JUCO'),
    ('Brookdale Community College', 'JUCO'),
    ('Butler Community College', 'JUCO'),
    ('Casper College', 'JUCO'),
    ('Chipola College', 'JUCO'),
    ('Cochise College', 'JUCO'),
    ('College of DuPage', 'JUCO'),
    ('College of Southern Nevada', 'JUCO'),
    ('Cowley College', 'JUCO'),
    ('Eastern Florida State College', 'JUCO'),
    ('Eastern Oklahoma State College', 'JUCO'),
    ('Ellsworth Community College', 'JUCO'),
    ('El Paso Community College', 'JUCO'),
    ('Feather River College', 'JUCO'),
    ('Florida Keys Community College', 'JUCO'),
    ('Fresno City College', 'JUCO'),
    ('Fullerton College', 'JUCO'),
    ('Garden City Community College', 'JUCO'),
    ('Glendale Community College', 'JUCO'),
    ('Grand Rapids Community College', 'JUCO'),
    ('Gulf Coast State College', 'JUCO'),
    ('Harper College', 'JUCO'),
    ('Herkimer County Community College', 'JUCO'),
    ('Hillsborough Community College', 'JUCO'),
    ('Howard College', 'JUCO'),
    ('Hudson Valley Community College', 'JUCO'),
    ('Hutchinson Community College', 'JUCO'),
    ('Iowa Central Community College', 'JUCO'),
    ('Iowa Lakes Community College', 'JUCO'),
    ('Jackson State Community College', 'JUCO'),
    ('Jefferson College', 'JUCO'),
    ('Joliet Junior College', 'JUCO'),
    ('Kansas City Kansas Community College', 'JUCO'),
    ('Kilgore College', 'JUCO'),
    ('Lackawanna College', 'JUCO'),
    ('Lake Land College', 'JUCO'),
    ('Lamar Community College', 'JUCO'),
    ('Laredo Community College', 'JUCO'),
    ('Lee College', 'JUCO'),
    ('Lehigh Carbon Community College', 'JUCO'),
    ('Lewis and Clark Community College', 'JUCO'),
    ('Lincoln Land Community College', 'JUCO'),
    ('Long Beach City College', 'JUCO'),
    ('Louisburg College', 'JUCO'),
    ('McLennan Community College', 'JUCO'),
    ('Merced College', 'JUCO'),
    ('Mesa Community College', 'JUCO'),
    ('Miami Dade College', 'JUCO'),
    ('Midland College', 'JUCO'),
    ('Monroe Community College', 'JUCO'),
    ('Monterey Peninsula College', 'JUCO'),
    ('Mt. Hood Community College', 'JUCO'),
    ('Nassau Community College', 'JUCO'),
    ('Navarro College', 'JUCO'),
    ('New Mexico Junior College', 'JUCO'),
    ('New Mexico Military Institute', 'JUCO'),
    ('North Iowa Area Community College', 'JUCO'),
    ('Northeast Mississippi Community College', 'JUCO'),
    ('Northwest Florida State College', 'JUCO'),
    ('Odessa College', 'JUCO'),
    ('Pasco-Hernando State College', 'JUCO'),
    ('Pensacola State College', 'JUCO'),
    ('Phoenix College', 'JUCO'),
    ('Polk State College', 'JUCO'),
    ('Pratt Community College', 'JUCO'),
    ('Riverside City College', 'JUCO'),
    ('Rock Valley College', 'JUCO'),
    ('Sacramento City College', 'JUCO'),
    ('Salt Lake Community College', 'JUCO'),
    ('San Bernardino Valley College', 'JUCO'),
    ('San Jacinto College', 'JUCO'),
    ('Santa Ana College', 'JUCO'),
    ('Santa Barbara City College', 'JUCO'),
    ('Santa Monica College', 'JUCO'),
    ('Scottsdale Community College', 'JUCO'),
    ('Seminole State College', 'JUCO'),
    ('Seward County Community College', 'JUCO'),
    ('Shelton State Community College', 'JUCO'),
    ('Sierra College', 'JUCO'),
    ('Sinclair Community College', 'JUCO'),
    ('Snow College', 'JUCO'),
    ('South Plains College', 'JUCO'),
    ('State Fair Community College', 'JUCO'),
    ('Tallahassee Community College', 'JUCO'),
    ('Temple College', 'JUCO'),
    ('Texas State Technical College', 'JUCO'),
    ('Three Rivers Community College', 'JUCO'),
    ('Treasure Valley Community College', 'JUCO'),
    ('Trinity Valley Community College', 'JUCO'),
    ('Tyler Junior College', 'JUCO'),
    ('Ventura College', 'JUCO'),
    ('Victoria College', 'JUCO'),
    ('Vincennes University', 'JUCO'),
    ('Wallace State Community College', 'JUCO'),
    ('Waubonsee Community College', 'JUCO'),
    ('Western Nevada College', 'JUCO'),
    ('Western Wyoming Community College', 'JUCO'),
    ('Yavapai College', 'JUCO')
ON CONFLICT (name) DO NOTHING;

COMMIT; 