import React from 'react';
import LegalPageLayout from '../components/LegalPageLayout';
import Footer from '../components/Footer';

export default function Disclaimer() {
  return (
    <>
      <LegalPageLayout title="FairPlay NIL LLC – Disclaimer">
      <h2>1. Informational and Educational Use Only</h2>
      <p>
        The information, tools, and results provided by <strong>FairPlay NIL LLC</strong> ("<strong>FairPlay NIL</strong>," "<strong>we</strong>," "<strong>us</strong>," or "<strong>our</strong>") — including outputs from the <strong>Fair Market Value (FMV) Calculator</strong>, <strong>Deal Builder</strong>, <strong>Pre-Clearance Check</strong>, and any dashboards, analytics, or APIs (collectively, the "<strong>Service</strong>") — are provided <strong>for informational and educational purposes only</strong>.
      </p>
      <p>
        FairPlay NIL does <strong>not</strong> provide legal, compliance, accounting, tax, or financial advice.  
        All data, valuations, and compliance risk flags are <strong>estimates or opinions</strong> generated by algorithms and business logic based on limited input data.  
        You should not rely on these results as a substitute for advice from qualified professionals or as a definitive determination of any deal's legality or fair market value.
      </p>

      <h2>2. No Guarantee of Accuracy or Outcomes</h2>
      <p>
        While FairPlay NIL strives to ensure that the data and models underlying the Service are reliable, <strong>we make no representation or warranty</strong> as to the accuracy, completeness, or applicability of any estimate, score, or recommendation.
      </p>
      <p>All outputs are <strong>non-binding</strong> and do <strong>not guarantee</strong> or predict any decision, approval, or ruling by:</p>
      <ul>
        <li>the NCAA,</li>
        <li>any conference or athletic association,</li>
        <li>any school or university compliance office,</li>
        <li>any government or regulatory authority, or</li>
        <li>any collective or affiliated organization.</li>
      </ul>
      <p>You are solely responsible for verifying your deal information, ensuring compliance with applicable NIL rules, and obtaining all required institutional and regulatory approvals.</p>

      <h2>3. No Endorsement or Affiliation</h2>
      <p>
        References to or use of <strong>third-party data sources</strong>, such as publicly available NIL databases, FOIA datasets, news reports, or institutional records, are for contextual and analytical purposes only.  
        Such references <strong>do not imply endorsement, partnership, or verification</strong> by those third parties.
      </p>
      <p>Similarly, mention of any university, athlete, brand, or organization within the Service does <strong>not constitute sponsorship or approval</strong> by those entities.</p>

      <h2>4. User Responsibility</h2>
      <p>You understand and agree that:</p>
      <ul>
        <li>You are solely responsible for any decisions or actions you take based on outputs from FairPlay NIL.</li>
        <li>You remain responsible for ensuring compliance with all NCAA, conference, state, school, and institutional NIL policies and disclosure requirements.</li>
        <li>You assume full responsibility for any business or compliance consequences resulting from your reliance on FairPlay NIL's tools or data.</li>
      </ul>

      <h2>5. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, <strong>FairPlay NIL LLC</strong> disclaims all liability for any loss, damage, or adverse consequence arising from your use of, or reliance on, the Service or its outputs.  
        Use of the Service constitutes acceptance of this limitation.
      </p>

      <h2>6. Contact Information</h2>
      <p>Questions or concerns about this Disclaimer may be directed to:</p>
      <p>
        <strong>Email:</strong> <a href="mailto:wachtelj22@gmail.com">wachtelj22@gmail.com</a><br/>
        <strong>Mail:</strong> FairPlay NIL LLC, Charlottesville, Virginia, USA
      </p>

      <hr/>
      <p><strong>© 2025 FairPlay NIL LLC. All rights reserved.</strong></p>
      </LegalPageLayout>
      <Footer />
    </>
  );
}
