import React from 'react';
import LegalPageLayout from '../components/LegalPageLayout';
import Footer from '../components/Footer';

export default function TermsOfUse() {
  return (
    <>
      <LegalPageLayout title="FairPlay NIL LLC – Terms of Use">
      <h2>1. Overview</h2>
      <p>
        These Terms of Use ("<strong>Terms</strong>") govern your access to and use of the FairPlay NIL website, web application, and related services (collectively, the "<strong>Service</strong>") operated by <strong>FairPlay NIL LLC</strong> ("<strong>FairPlay NIL</strong>," "<strong>we</strong>," "<strong>us</strong>," or "<strong>our</strong>").  
        By accessing or using the Service, you agree to be bound by these Terms and our <a href="/privacy">Privacy Policy</a> and <a href="/cookies">Cookie Policy</a>.  
        If you do not agree, please discontinue use immediately.
      </p>

      <h2>2. The Service</h2>
      <p>
        FairPlay NIL provides digital tools to help users understand and manage <strong>Name-Image-Likeness (NIL)</strong> deal valuation and compliance processes.  
        Features may include:
      </p>
      <ul>
        <li><strong>FMV Calculator</strong> – estimates of fair market value;</li>
        <li><strong>Deal Builder and Pre-Clearance Check</strong> – structured NIL documentation and review tools;</li>
        <li><strong>Analytics Dashboards</strong> – optional insights and reporting; and</li>
        <li><strong>APIs or Integrations</strong> – data access for authorized partners.</li>
      </ul>
      <p>We may modify, suspend, or discontinue features at any time without liability or notice.</p>

      <h2>3. Informational Use Only – No Legal, Compliance, or Tax Advice</h2>
      <p>
        All data, scores, valuations, or recommendations generated by FairPlay NIL are <strong>for informational and educational purposes only</strong>.  
        FairPlay NIL LLC is <strong>not a law firm</strong> and does not provide legal, compliance, accounting, or tax advice.  
        Use of the Service does <strong>not</strong> create an attorney-client or fiduciary relationship.  
        You should obtain independent advice from qualified professionals before relying on any information produced by the Service.
      </p>

      <h2>4. No Guarantee of Outcomes</h2>
      <p>
        Any FMV estimate, compliance score, or deal-risk indicator provided through the Service is a non-binding prediction.  
        FairPlay NIL LLC makes <strong>no guarantee</strong> that any deal will be approved, accepted, or compliant with regulations of the NCAA, conferences, schools, or government agencies.
      </p>

      <h2>5. Eligibility and Accounts</h2>
      <p>
        You must be at least <strong>18 years old</strong> (or the age of majority in your jurisdiction) to create an account.  
        Users aged <strong>16–17</strong> may use the Service only with consent from a parent, guardian, or authorized school official.  
        You are responsible for maintaining the confidentiality of your credentials and for all activities under your account.  
        Notify us immediately of unauthorized use.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree <strong>not</strong> to:</p>
      <ol>
        <li>Use the Service for unlawful, deceptive, or harmful purposes;</li>
        <li>Attempt to interfere with or reverse engineer the Service;</li>
        <li>Upload or distribute content that violates any rights or applicable laws;</li>
        <li>Circumvent NCAA, school, or state NIL compliance processes; or</li>
        <li>Misrepresent FairPlay NIL outputs as official determinations or endorsements.</li>
      </ol>

      <h2>7. User Content and License</h2>
      <p>
        You retain ownership of all data, deal information, documents, and materials you upload ("<strong>User Content</strong>").  
        By submitting User Content, you grant FairPlay NIL LLC a <strong>non-exclusive, worldwide, royalty-free license</strong> to host, process, analyze, and display that content as necessary to operate, secure, and improve the Service.  
        You represent that you have lawful rights to all submitted data and that sharing it does not violate FERPA, school policies, or confidentiality agreements.
      </p>

      <h2>8. Third-Party Data and Services</h2>
      <p>
        FairPlay NIL may reference or integrate external datasets (e.g., NIL databases, FOIA reports) and third-party services (e.g., Supabase, Vercel, Render, Stripe, analytics).  
        We do not control these third parties and are <strong>not responsible</strong> for their accuracy, availability, or practices.  
        Use of third-party services is subject to their own terms and privacy policies.
      </p>

      <h2>9. Fees and Billing</h2>
      <p>
        Some features may require payment through <strong>Stripe</strong> or another authorized processor.  
        All fees are charged as posted and are <strong>non-refundable</strong>, except as required by law.  
        Applicable taxes may apply.  
        Failure to pay may result in suspension or termination of your account.
      </p>

      <h2>10. Confidentiality</h2>
      <p>
        Each party may receive non-public or proprietary information ("<strong>Confidential Information</strong>").  
        The receiving party will use such information only for purposes consistent with these Terms and will protect it with reasonable care.  
        This section does not limit our processing of personal data described in our Privacy Policy.
      </p>

      <h2>11. Intellectual Property</h2>
      <p>
        All software, designs, algorithms, trademarks, and content in the Service are owned by or licensed to <strong>FairPlay NIL LLC</strong>.  
        Except as expressly granted, no license or ownership interest is transferred to you.  
        You may not reproduce, distribute, or modify any part of the Service without prior written consent.
      </p>

      <h2>12. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "<strong>AS IS</strong>" AND "<strong>AS AVAILABLE</strong>."  
        FAIRPLAY NIL LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.  
        WE DO NOT WARRANT THAT THE SERVICE OR ITS OUTPUTS WILL BE ACCURATE, ERROR-FREE, OR UNINTERRUPTED.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, FAIRPLAY NIL LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL.  
        OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS SHALL NOT EXCEED THE GREATER OF:
      </p>
      <p>(A) THE AMOUNTS PAID BY YOU IN THE 12 MONTHS BEFORE THE CLAIM, OR</p>
      <p>(B) <strong>USD $1,000</strong>.</p>

      <h2>14. Indemnification</h2>
      <p>You agree to defend, indemnify, and hold harmless FairPlay NIL LLC, its officers, employees, and agents from any claims, damages, or expenses (including attorneys' fees) arising out of your:</p>
      <p>(a) use of the Service;</p>
      <p>(b) User Content; or</p>
      <p>(c) violation of these Terms or applicable law.</p>

      <h2>15. Termination</h2>
      <p>
        We may suspend or terminate your account at any time for violation of these Terms or if necessary to protect the integrity of the Service.  
        You may terminate by deleting your account.  
        Sections 3–14 survive termination.
      </p>

      <h2>16. Governing Law and Dispute Resolution</h2>
      <p>
        These Terms are governed by the laws of the <strong>Commonwealth of Virginia</strong>, excluding its conflict-of-laws rules.  
        Any dispute shall be resolved by <strong>binding arbitration</strong> in <strong>Charlottesville, Virginia</strong>, under the rules of the <strong>American Arbitration Association (AAA)</strong>.  
        Arbitration shall occur on an <strong>individual basis only</strong> — class or representative actions are not permitted.  
        Either party may seek injunctive relief in a Virginia court to protect intellectual-property or confidentiality rights.
      </p>

      <h2>17. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time.  
        When we make material changes, we will update the <strong>Effective Date</strong> and notify users by email or within the Service.  
        Your continued use of the Service after the update constitutes acceptance of the revised Terms.
      </p>

      <h2>18. Contact Us</h2>
      <p>Questions, feedback, or legal notices may be directed to:</p>
      <p>
        <strong>Email:</strong> <a href="mailto:wachtelj22@gmail.com">wachtelj22@gmail.com</a><br/>
        <strong>Mail:</strong> FairPlay NIL LLC, Charlottesville, Virginia, USA
      </p>

      <hr/>
      <p><strong>Last Updated:</strong> October 1, 2025</p>
      <p><strong>© 2025 FairPlay NIL LLC. All rights reserved.</strong></p>
      </LegalPageLayout>
      <Footer />
    </>
  );
}
