import React from 'react';
import LegalPageLayout from '../components/LegalPageLayout';

export default function TermsOfService() {
  return (
    <LegalPageLayout title="FairPlay NIL LLC – Terms of Service">
      <h2>1. Agreement to Terms</h2>
      <p>
        These Terms of Service ("<strong>Terms</strong>") constitute a legally binding agreement between you ("<strong>you</strong>" or "<strong>user</strong>") and <strong>FairPlay NIL LLC</strong> ("<strong>FairPlay NIL</strong>," "<strong>we</strong>," "<strong>us</strong>," or "<strong>our</strong>") governing your access to and use of the FairPlay NIL website, applications, APIs, and related services (collectively, the "<strong>Service</strong>").  
      </p>
      <p>
        By creating an account, accessing, or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms, along with our <a href="/privacy">Privacy Policy</a>, <a href="/disclaimer">Disclaimer</a>, and <a href="/cookies">Cookie Policy</a>.  
        If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of the Service</h2>
      <p>
        FairPlay NIL provides a digital compliance and valuation platform that helps student-athletes, institutions, and collectives analyze and document Name-Image-Likeness ("<strong>NIL</strong>") transactions.  
        Our Service includes, but is not limited to:
      </p>
      <ul>
        <li><strong>FMV Calculator</strong> – generates non-binding estimates of fair market value for NIL deals;</li>
        <li><strong>Deal Builder & Pre-Clearance Check</strong> – enables compliant contract documentation and pre-review;</li>
        <li><strong>Analytics Dashboards & APIs</strong> – provide insights and recordkeeping tools for participating institutions.</li>
      </ul>
      <p>We may modify, suspend, or discontinue any feature at any time without notice.</p>

      <h2>3. No Legal, Compliance, or Tax Advice</h2>
      <p>
        All data, outputs, and insights provided through the Service are <strong>for informational and educational purposes only</strong>.  
        FairPlay NIL LLC is <strong>not a law firm</strong> and does not provide legal, tax, or compliance advice.  
        Use of the Service does <strong>not</strong> create an attorney-client, advisor, or fiduciary relationship.  
        You should consult qualified professionals before relying on any information or recommendations generated by the Service.
      </p>

      <h2>4. Account Registration and Responsibility</h2>
      <p>To access certain features, you must register for an account. You agree to:</p>
      <ul>
        <li>Provide accurate and current information;</li>
        <li>Maintain the security of your credentials; and</li>
        <li>Accept responsibility for all activity that occurs under your account.</li>
      </ul>
      <p>We may suspend or terminate your access if we suspect unauthorized use, security risk, or violation of these Terms.</p>

      <h2>5. Eligibility</h2>
      <p>
        You must be <strong>18 years or older</strong> (or the age of majority in your jurisdiction) to use the Service.  
        If you are between <strong>16–17 years old</strong>, you may use the Service only with the consent and supervision of a parent, guardian, or authorized institutional representative.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ol>
        <li>Use the Service for any illegal or fraudulent purpose;</li>
        <li>Interfere with or disrupt the functionality of the Service;</li>
        <li>Reverse-engineer, scrape, or decompile the Service;</li>
        <li>Upload content that is unlawful, misleading, or infringes on others' rights;</li>
        <li>Misrepresent outputs as official NIL or NCAA determinations; or</li>
        <li>Attempt to gain unauthorized access to our systems or data.</li>
      </ol>
      <p>Violation of this section may result in immediate suspension or termination of access.</p>

      <h2>7. User Content and License</h2>
      <p>
        You retain all ownership rights to any data, deals, attachments, and other content you upload or submit ("<strong>User Content</strong>").  
        By using the Service, you grant FairPlay NIL LLC a <strong>non-exclusive, worldwide, royalty-free license</strong> to host, process, analyze, and display your User Content as necessary to:
      </p>
      <ul>
        <li>Provide, improve, and secure the Service;</li>
        <li>Maintain audit trails; and</li>
        <li>Ensure data integrity and compliance.</li>
      </ul>
      <p>You represent that you have the legal right to provide all submitted content and that your submission does not violate FERPA, institutional rules, or applicable laws.</p>

      <h2>8. Fees, Billing, and Payments</h2>
      <p>
        Certain portions of the Service may require payment through our third-party processor, <strong>Stripe</strong>.  
        By submitting payment information, you authorize FairPlay NIL LLC (and Stripe) to charge applicable fees for your selected plan or transaction.
      </p>
      <ul>
        <li>All fees are stated in U.S. dollars unless otherwise noted.</li>
        <li>Fees are <strong>non-refundable</strong>, except as required by law.</li>
        <li>Applicable taxes may apply based on your location.</li>
        <li>Failure to pay may result in suspension or termination of access.</li>
      </ul>
      <p>We reserve the right to modify pricing with reasonable notice.</p>

      <h2>9. Third-Party Services</h2>
      <p>Our Service may integrate with or rely upon third-party providers, including:</p>
      <ul>
        <li><strong>Vercel</strong> (frontend hosting)</li>
        <li><strong>Render</strong> (backend hosting)</li>
        <li><strong>Supabase</strong> (database, authentication, storage)</li>
        <li><strong>Stripe</strong> (payments)</li>
        <li><strong>Postmark / SendGrid</strong> (email delivery)</li>
        <li><strong>Sentry</strong> (error tracking)</li>
        <li><strong>Analytics providers</strong></li>
      </ul>
      <p>These third parties operate under their own terms and privacy policies. We are not responsible for their actions, content, or availability.</p>

      <h2>10. Confidentiality</h2>
      <p>
        Each party agrees to protect the other's confidential information with reasonable care and not to disclose it except as necessary to perform obligations under these Terms or as required by law.  
        This section does not restrict FairPlay NIL from using anonymized or aggregated data for analytics or product improvement.
      </p>

      <h2>11. Intellectual Property Rights</h2>
      <p>
        The Service, including software, algorithms, text, graphics, design, and trademarks, are owned by or licensed to <strong>FairPlay NIL LLC</strong>.  
        All rights not expressly granted are reserved.  
        You may not copy, modify, distribute, or create derivative works from any part of the Service without written authorization.
      </p>
      <p>You grant FairPlay NIL permission to use your feedback or suggestions without obligation or compensation.</p>

      <h2>12. Beta and Experimental Features</h2>
      <p>
        Certain features may be labeled as "Beta," "Preview," or "Experimental."  
        These features are provided <em>as is</em> and may contain bugs or undergo significant changes.  
        Use of such features is at your own risk.
      </p>

      <h2>13. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "<strong>AS IS</strong>" AND "<strong>AS AVAILABLE</strong>."  
        FAIRPLAY NIL LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.  
        WE DO NOT WARRANT THAT OUTPUTS WILL BE ACCURATE, ERROR-FREE, OR SUITABLE FOR YOUR INTENDED USE.  
        YOUR USE OF THE SERVICE IS AT YOUR OWN RISK.
      </p>

      <h2>14. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, FAIRPLAY NIL LLC AND ITS DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL.
      </p>
      <p>OUR TOTAL LIABILITY FOR ALL CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF:</p>
      <p>(A) THE AMOUNTS YOU PAID TO US IN THE 12 MONTHS PRIOR TO THE CLAIM, OR</p>
      <p>(B) <strong>USD $1,000</strong>.</p>

      <h2>15. Indemnification</h2>
      <p>You agree to indemnify, defend, and hold harmless FairPlay NIL LLC, its officers, employees, and agents from any claims, liabilities, damages, or expenses (including reasonable attorneys' fees) arising from:</p>
      <ul>
        <li>Your use of the Service;</li>
        <li>Your User Content; or</li>
        <li>Your violation of these Terms or applicable law.</li>
      </ul>

      <h2>16. Termination</h2>
      <p>
        You may terminate your account at any time by contacting us at <a href="mailto:wachtelj22@gmail.com">wachtelj22@gmail.com</a>.  
        We may suspend or terminate your access for any reason, including breach of these Terms or risk to the Service.  
        Upon termination, your right to use the Service ceases immediately, and sections <strong>3–15</strong> will survive.
      </p>

      <h2>17. Governing Law and Dispute Resolution</h2>
      <p>
        These Terms are governed by the laws of the <strong>Commonwealth of Virginia</strong>, excluding its conflict-of-laws principles.  
        All disputes shall be resolved through <strong>binding arbitration</strong> in <strong>Charlottesville, Virginia</strong>, conducted by the <strong>American Arbitration Association (AAA)</strong> under its commercial rules.  
        Arbitration shall occur on an <strong>individual basis only</strong>.  
        Either party may seek injunctive relief in a Virginia court to protect intellectual property or confidentiality.
      </p>

      <h2>18. Modifications to These Terms</h2>
      <p>
        We may update or revise these Terms periodically.  
        When we make material changes, we will update the <strong>Effective Date</strong> and notify you via email or within the Service.  
        Your continued use constitutes acceptance of the revised Terms.
      </p>

      <h2>19. Contact Information</h2>
      <p>For questions, feedback, or legal notices:</p>
      <p>
        <strong>Email:</strong> <a href="mailto:wachtelj22@gmail.com">wachtelj22@gmail.com</a><br/>
        <strong>Mail:</strong> FairPlay NIL LLC, Charlottesville, Virginia, USA
      </p>

      <hr/>
      <p><strong>Last Updated:</strong> October 1, 2025</p>
      <p><strong>© 2025 FairPlay NIL LLC. All rights reserved.</strong></p>
    </LegalPageLayout>
  );
}
